# Many thanks to
# https://github.com/sbstjn/typescript-npm-boilerplate/blob/master/.circleci/config.yml
# for serving as great example config

# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

whitelist: &whitelist
  paths:
    - .npmignore
    - coverage/*
    - dist/*
    - node_modules/*
    - src/*
    - test/*
    - package.json
    - README.md
    - tsconfig.json
    - tslint.json
    - jest.config.js
    - types/*

jobs:
  checkout:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  lint:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Lint TypeScript code
          command: npm run lint

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Test TypeScript code and get coverage
          command: npm run test:coverage

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  coveralls:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Submit coverage report to Coveralls.io
          command: npm run coveralls

  build:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Build TypeScript code
          command: npm run build

      - persist_to_workspace:
          root: ~/repo
          <<: *whitelist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: npx semantic-release

workflows:
  build:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - lint:
          requires:
            - checkout
      - coveralls:
          requires:
            - test
      - build:
          requires:
            - test
            - lint

  # release should only run on master
  release:
    jobs:
      - checkout:
          filters:
            branches:
              only: master
      - test:
          filters:
            branches:
              only: master
          requires:
            - checkout
      - lint:
          filters:
            branches:
              only: master
          requires:
            - checkout
      - coveralls:
          filters:
            branches:
              only: master
          requires:
            - test
      - build:
          filters:
            branches:
              only: master
          requires:
            - test
            - lint
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - build
